# Generated by Django 6.0.1 on 2026-06-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='stage',
            field=models.CharField(choices=[('creche', 'Creche'), ('nursery', 'Nursery'), ('kg', 'KG'), ('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('jhs', 'JHS'), ('shs', 'SHS')], max_length=20),
        ),
    ]
