# Generated by Django 6.0.1 on 2026-06-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_schoolclass_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='attendance_mode',
            field=models.CharField(choices=[('subject', 'Subject Teacher'), ('class_teacher', 'Class Teacher')], default='subject', max_length=20),
        ),
    ]
