# Generated by Django 6.0.1 on 2026-08-27 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
