# Generated by Django 6.0.1 on 2026-08-27 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paymenttransaction_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
