# Generated by Django 6.0.1 on 2026-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schoolsetting_attendance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='gps_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
