# Generated by Django 6.0.1 on 2026-06-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_schoolsetting_email_schoolsetting_gps_address'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_class_time',
        ),
    ]
