# Generated by Django 6.0.1 on 2026-09-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paymenttransaction_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('proprietor', 'Proprietor'), ('proprietress', 'Proprietress'), ('board_director', 'Board of Directors'), ('headmaster', 'Headmaster'), ('headmistress', 'Headmistress'), ('accountant', 'Accountant'), ('bursar', 'Bursar'), ('hod', 'Head of Department'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('support_staff', 'Support Staff - Kitchen/Garden/Security/Canteen/Attendant/Driver/Cleaner')], max_length=20),
        ),
    ]
