# Generated by Django 6.0.1 on 2026-09-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic (Nursery - JHS)'), ('shs', 'Senior High School'), ('basic_shs', 'Basic + Senior High School (Nursery - SHS)')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss.'), ('Dr', 'Dr.'), ('Prof', 'Prof.'), ('Rev', 'Rev.'), ('Hon', 'Hon.'), ('Sir', 'Sir.')], max_length=10, null=True),
        ),
    ]
