# Generated by Django 6.0.1 on 2026-06-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_timetable_unique_class_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_teacher_time',
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('teacher', 'weekday', 'start_time', 'end_time'), name='unique_teacher_time'),
        ),
    ]
