# Generated by Django 6.0.1 on 2026-09-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_school_level_alter_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='edition',
            field=models.CharField(choices=[('full', 'Full School Management System'), ('basic', 'Basic / Custom School System')], default='full', max_length=10),
        ),
    ]
