# Generated by Django 6.0.1 on 2026-06-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_announcement_announcementread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_group',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'All Students'), ('parents', 'All Parents'), ('teachers', 'All Teachers'), ('accountants', 'All Accountants'), ('staff', 'All Staff'), ('students_teachers', 'Students + Teachers'), ('specific_class', 'Specific Class'), ('non_teaching', 'Non-Teaching Staff Only')], default='all', max_length=20),
        ),
    ]
