# Generated by Django 6.0.1 on 2026-06-28 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_announcement_target_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='acknowledged_by',
            field=models.ManyToManyField(blank=True, help_text="Tracks which users clicked 'I Understand'", related_name='acknowledged_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='action_url',
            field=models.URLField(blank=True, help_text='Optional: Link button to fees page, etc. Example: /fees/pay/', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('low', 'Info Only - Small banner at top'), ('medium', 'Important - Popup, can dismiss'), ('high', 'Critical - Must acknowledge to continue')], default='low', help_text='How urgently should users see this?', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_group',
            field=models.CharField(choices=[('all', 'All Users'), ('students', ' Students'), ('parents', ' Parents'), ('teachers', ' Teachers'), ('accountants', ' Accountants'), ('staff', ' Staff'), ('students_teachers', 'Students + Teachers'), ('specific_class', 'Specific Class'), ('non_teaching', 'Non-Teaching Staff Only')], default='all', max_length=20),
        ),
    ]
