# Generated by Django 6.0.1 on 2026-09-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_basicdailyfeecollection_basicdailyfeesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdailyfeecollection',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basic_daily_fee_collections', to='accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='basicdailyfeecollection',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basic_daily_fee_collections', to='accounts.term'),
        ),
    ]
