# Generated by Django 6.0.1 on 2026-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_announcement_acknowledged_by_announcement_action_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='momo_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='School MoMo Number'),
        ),
        migrations.AddField(
            model_name='school',
            name='payment_mode',
            field=models.CharField(choices=[('none', 'Disabled - Cash Only'), ('manual', 'Manual - Show MoMo/Bank Details'), ('automatic', 'Automatic - Paystack/Flutterwave')], default='none', help_text='How should students pay fees online?', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='paystack_secret_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
