# Generated by Django 6.0.1 on 2026-09-13 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_basicdailyfeecollection_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdailyfeecollection',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basic_daily_fee_collections', to='accounts.academicyear'),
        ),
        migrations.AlterField(
            model_name='basicdailyfeecollection',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basic_daily_fee_collections', to='accounts.term'),
        ),
    ]
