# Generated by Django 6.0.1 on 2026-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_school_account_name_school_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='flutterwave_public_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='flutterwave_secret_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='hubtel_client_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='hubtel_client_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='hubtel_merchant_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hubtel Merchant Account Number'),
        ),
        migrations.AddField(
            model_name='school',
            name='momo_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School MoMo Name'),
        ),
        migrations.AddField(
            model_name='school',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('hubtel', 'Hubtel'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='hubtel', help_text='Select gateway if mode is Automatic', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='payment_mode',
            field=models.CharField(choices=[('disabled', 'Disabled - No online payments'), ('cash', 'Cash Only - Pay at school'), ('manual', 'Manual - Show MoMo/Bank Details'), ('automatic', 'Automatic - Online Gateway')], default='disabled', help_text='How should students pay fees online?', max_length=10),
        ),
    ]
