# Generated by Django 6.0.1 on 2026-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_basicdailyfeecollection_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='sba_total',
            field=models.IntegerField(default=80, help_text='Maximum raw SBA marks for this term'),
        ),
    ]
