# Generated by Django 6.0.1 on 2026-06-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_school_flutterwave_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accept_automatic',
            field=models.BooleanField(default=False, verbose_name='Online Gateway'),
        ),
        migrations.AddField(
            model_name='school',
            name='accept_cash',
            field=models.BooleanField(default=False, verbose_name='Cash at School'),
        ),
        migrations.AddField(
            model_name='school',
            name='accept_manual',
            field=models.BooleanField(default=False, verbose_name='Manual Transfer'),
        ),
        migrations.AlterField(
            model_name='school',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('hubtel', 'Hubtel'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='hubtel', help_text='Select gateway if Online Gateway is enabled', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='payment_mode',
            field=models.CharField(choices=[('disabled', 'Disabled - No online payments'), ('cash', 'Cash Only - Pay at school'), ('manual', 'Manual - Show MoMo/Bank Details'), ('automatic', 'Automatic - Online Gateway')], default='disabled', help_text='OLD - Keep for now', max_length=10),
        ),
    ]
