# Generated by Django 6.0.1 on 2026-09-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_term_sba_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='sba_total',
            field=models.IntegerField(help_text='Maximum raw SBA marks for this term'),
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remark', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='accounts.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='accounts.term')),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
    ]
