# Generated by Django 6.0.1 on 2026-06-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_school_accept_automatic_school_accept_cash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='amount',
            new_name='amount_due',
        ),
        migrations.AddField(
            model_name='fee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.CharField(default='School Fees', max_length=200),
        ),
        migrations.AddField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
