# Generated by Django 6.0.1 on 2026-06-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_amount_fee_amount_due_fee_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
