# Generated by Django 6.0.1 on 2026-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_feestructure_due_date_alter_studentfee_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
