# Generated by Django 6.0.1 on 2026-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_feestructure_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accept_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='accept_momo',
            field=models.BooleanField(default=False),
        ),
    ]
