# Generated by Django 6.0.4 on 2026-09-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_reset_admin_password_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='attendance_radius',
            field=models.PositiveIntegerField(default=100, help_text='Maximum distance from the school where teachers can check in.', verbose_name='Teacher Attendance Radius (metres)'),
        ),
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='School Latitude'),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='School Longitude'),
        ),
    ]
