# Generated by Django 6.0.1 on 2026-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('bank', 'Bank Transfer'), ('paystack', 'Paystack'), ('hubtel', 'Hubtel')], default='cash', max_length=20),
        ),
    ]
