# Generated by Django 6.0.1 on 2026-07-10 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('momo', 'Mobile Money')], max_length=10)),
                ('reference_number', models.CharField(help_text='Bank txn ID or MoMo txn ID', max_length=100)),
                ('paid_at', models.DateTimeField(help_text='Date/time parent made the payment')),
                ('proof_image', models.ImageField(help_text='Upload screenshot or photo of receipt', upload_to='payment_proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.academicyear')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payment_source', to='accounts.paymenttransaction')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='pending_payments', to=settings.AUTH_USER_MODEL)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payments', to='accounts.studentfee')),
                ('submitted_by', models.ForeignKey(limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payments', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.term')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['accountant', 'bursar', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Payment',
                'verbose_name_plural': 'Pending Payments',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
