# Generated by Django 6.0.1 on 2026-07-11 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_pendingpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pending_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.pendingpayment')),
            ],
        ),
    ]
