# Generated by Django 6.0.1 on 2026-07-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_pendingpaymentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpaymentitem',
            name='paid_field',
            field=models.CharField(default='unknown', help_text='StudentFee paid field to update after approval', max_length=100),
            preserve_default=False,
        ),
    ]
