# Generated by Django 6.0.1 on 2026-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_pendingpaymentitem_paid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text="Parent's bank/momo reference", max_length=100, null=True),
        ),
    ]
