# Generated by Django 6.0.1 on 2026-07-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_notification_notificationrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin/Proprietor'), ('board_director', 'Board of Directors'), ('headmaster', 'Headmaster'), ('accountant', 'Accountant'), ('bursar', 'Bursar'), ('hod', 'Head of Department'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('support_staff', 'Support Staff - Kitchen/Garden/Security/Canteen/Attendant/Driver/Cleaner')], max_length=20),
        ),
    ]
