# Generated by Django 6.0.1 on 2026-07-19 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='target_group',
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text='Stores ticked roles'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='acknowledged_by',
            field=models.ManyToManyField(blank=True, related_name='acknowledged_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='action_url',
            field=models.URLField(blank=True, help_text='Optional link', null=True),
        ),
    ]
