# Generated by Django 6.0.1 on 2026-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_announcement_target_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_group',
            field=models.CharField(default='All Users', max_length=100),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
