# Generated by Django 6.0.1 on 2026-07-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_notification_target_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='mnotify_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='mnotify_sender_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable SMS Notifications'),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('hubtel', 'Hubtel (Recommended for Ghana)'), ('mnotify', 'MNotify')], default='hubtel', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_sender_id',
            field=models.CharField(blank=True, help_text='Max 11 chars, e.g. ADISSCH', max_length=11, null=True, verbose_name='SMS Sender ID e.g SCHOOL'),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_test_mode',
            field=models.BooleanField(default=True, verbose_name="SMS Test Mode - Don't send real SMS"),
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('provider', models.CharField(default='hubtel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
