# Generated by Django 6.0.1 on 2026-07-25 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_teacherattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={'ordering': ['-date', 'teacher__last_name', 'teacher__first_name'], 'verbose_name': 'Teacher Attendance', 'verbose_name_plural': 'Teacher Attendances'},
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('L', 'Late'), ('A', 'Absent'), ('LV', 'Leave'), ('S', 'Sick')], default='P', max_length=2),
        ),
    ]
