# Generated by Django 6.0.1 on 2026-07-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_teacherattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('L', 'Late'), ('A', 'Absent'), ('LV', 'Leave'), ('S', 'Sick'), ('E', 'Excused')], default='P', max_length=2),
        ),
    ]
