# Generated by Django 6.0.1 on 2026-07-27 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_teacherattendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='late_after_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='teacher_closing_time',
            field=models.TimeField(default='15:30'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='teacher_reporting_time',
            field=models.TimeField(default='07:30'),
        ),
    ]
