# Generated by Django 6.0.1 on 2026-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_schoolsetting_late_after_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='record_source',
            field=models.CharField(choices=[('self', 'Self Check-in'), ('staff', 'Staff Marked')], default='staff', max_length=10),
        ),
    ]
