# Generated by Django 6.0.1 on 2026-07-31 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_academicyear_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitem',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.paymenttype'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='paymenttype',
            unique_together={('school', 'code')},
        ),
    ]
