# Generated by Django 6.0.1 on 2026-07-31 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_paymentitem_payment_type_paymenttransaction_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='accounts.school'),
            preserve_default=False,
        ),
    ]
