# Generated by Django 6.0.1 on 2026-07-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_timetable_subject_alter_timetable_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='break_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='accounts.break'),
        ),
    ]
