# Generated by Django 6.0.1 on 2026-08-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_timetable_break_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='break',
            options={'ordering': ['stage', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='break',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='break',
            name='stage',
            field=models.CharField(choices=[('creche', 'Creche'), ('nursery', 'Nursery'), ('kg', 'KG'), ('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('jhs', 'JHS'), ('shs', 'SHS')], default='lower_primary', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='break',
            constraint=models.UniqueConstraint(fields=('school', 'stage', 'name', 'start_time', 'end_time'), name='unique_school_stage_break'),
        ),
    ]
