# Generated by Django 6.0.1 on 2026-08-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_break_options_alter_break_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academiccalendar',
            unique_together={('school', 'name', 'start_date', 'academic_year')},
        ),
    ]
