# Generated by Django 6.0.1 on 2026-08-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_academiccalendar_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuousassessment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
    ]
