# Generated by Django 6.0.1 on 2026-08-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_continuousassessment_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_type',
            field=models.CharField(blank=True, help_text='Father/Mother/Guardian', max_length=30, null=True),
        ),
    ]
