# Generated by Django 6.0.1 on 2026-08-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_message_school_result_school_timetable_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentremark',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
    ]
