# Generated by Django 6.0.1 on 2026-08-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_studentremark_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsubjectclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentsubjectclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectclass',
            unique_together={('student', 'subject', 'school_class', 'school')},
        ),
    ]
