# Generated by Django 6.0.1 on 2026-08-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_studentsubjectclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
    ]
