# Generated by Django 6.0.1 on 2026-05-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
